# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61i_server.proto\x12\x05\x61iapp\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"U\n\x0f\x44\x65tectionResult\x12!\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x12.aiapp.BoundingBox\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\x12\x0e\n\x06scores\x18\x03 \x03(\x02\"=\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"<\n\x11\x44\x65tectionResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.aiapp.DetectionResult2M\n\x12\x41iDetectionService\x12\x37\n\x06\x44\x65tect\x12\x13.aiapp.FrameRequest\x1a\x18.aiapp.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAMEREQUEST']._serialized_start=26
  _globals['_FRAMEREQUEST']._serialized_end=55
  _globals['_DETECTIONRESULT']._serialized_start=57
  _globals['_DETECTIONRESULT']._serialized_end=142
  _globals['_BOUNDINGBOX']._serialized_start=144
  _globals['_BOUNDINGBOX']._serialized_end=205
  _globals['_DETECTIONRESPONSE']._serialized_start=207
  _globals['_DETECTIONRESPONSE']._serialized_end=267
  _globals['_AIDETECTIONSERVICE']._serialized_start=269
  _globals['_AIDETECTIONSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
